version: "3.9"  # optional since v1.27.0

services:
  xrdp:
    build: .
#    image: debian-xrdp
    container_name: debian-xrdp
    ports:
        - "3389:3389"
#    command: -c "rm -f /var/run/xrdp/xrdp.pid && rm -f /var/run/xrdp/xrdp-sesman.pid && /usr/sbin/xrdp-sesman --nodaemon & /usr/sbin/xrdp -nodaemon"
    command: -c "/usr/sbin/xrdp-sesman --nodaemon & /usr/sbin/xrdp -nodaemon"
    tty: true
#    stdin_open: true
    entrypoint: /bin/sh
    environment:
    - TERM=xterm
